version: "3.9"

services:
  db:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: crud
    volumes:
      - mongo-data:/data/db
      - mongo-logs:/var/log/mongodb

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud_api
    restart: always
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=mongodb://db:27017/crud
      - NODE_ENV=production
    depends_on:
      - db
    # Optionnel : monter un volume pour le hot reload en dev
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo-data:
    driver: local
  mongo-logs:
